### ISSUE TITLE
Support::OS.windows? is not returning correct information; should test for ! nil 

### ISSUE THREAD

**Issue by weedySeaDragon** [rspec/rspec-support#220] opened 2015-07-04 00:43 UTC
The Regexp pattern matching operator in <code>Support::OS.windows?</code> returns the position of the first match, so a result of 0 (zero) is valid -- it means that there *was* a match with the first character of a pattern in the RegExp.  If no match is found, the pattern match operator will return *nil.*

The method should instead test to see if the pattern matching does not return nil:
```
   def windows?
       !(RbConfig::CONFIG['host_os'] =~ /cygwin|mswin|mingw|bccwin|wince|emx/).nil?
   end
```

I'm running Windows 7. Using IRB, you can see that RbConfig correctly reports my host_os.  The pattern matcher correctly returns 0 -- which is the position of the first char of the string that matches "mingw32".   RSpec::Support::OS.windows? says that I'm not running windows.
The last line shows the change that should be made to correctly evaluate the result of the pattern matching and whether the host_os is Windows.
```
>> RbConfig::CONFIG['host_os'] 
=> "mingw32"
>> RbConfig::CONFIG['host_os'] =~ /cygwin|mswin|mingw|bccwin|wince|emx/
=> 0
>> RSpec::Support::OS.windows?
=> 0
>> RSpec::Support::OS.windows? == true
=> false
>> !(RbConfig::CONFIG['host_os'] =~ /cygwin|mswin|mingw|bccwin|wince|emx/).nil?
=> true
```

**Comment by myronmarston** [comment] 2015-07-04 05:43
It's working as designed.  `0` is a truthy value in ruby.  It's common in Ruby to just use a predicate's truthiness value in a conditional (e.g. `if RSpec::Support::OS.windows?`).  I searched our code and confirmed that that's the only way we are using it:


```
rspec-core/lib/rspec/core/configuration.rb
715:        if RSpec::Support::OS.windows? && !ENV['ANSICON']
1705:      if RSpec::Support::OS.windows?

rspec-core/lib/rspec/core/shell_escape.rb
12:      if RSpec::Support::OS.windows?

rspec-core/spec/integration/persistence_failures_spec.rb
57:        if RSpec::Support::OS.windows?

rspec-core/spec/rspec/core/backtrace_formatter_spec.rb
143:        it "excludes lines from rspec libs by default", :unless => RSpec::Support::OS.windows? do

rspec-core/spec/rspec/core/bisect/runner_spec.rb
240:      RSpec::Support::OS.windows? || RSpec::Support::Ruby.jruby?

rspec-core/spec/rspec/core/configuration_options_spec.rb
7:  it "warns when HOME env var is not set", :unless => (RUBY_PLATFORM == 'java' || RSpec::Support::OS.windows?) do

rspec-core/spec/rspec/core/configuration_spec.rb
497:        it "loads files in Windows", :if => RSpec::Support::OS.windows? do
502:        it "loads files in Windows when directory is specified", :failing_on_appveyor, :if => RSpec::Support::OS.windows? do

rspec-core/spec/rspec/core/formatters/deprecation_formatter_spec.rb
114:        it "can handle when the stream is reopened to a system stream", :unless => RSpec::Support::OS.windows? do

rspec-core/spec/rspec/core/rake_task_spec.rb
43:    context "with space", :unless => RSpec::Support::OS.windows? do
50:    context "on windows, with a quote in the name", :if => RSpec::Support::OS.windows? do
77:      it "shellescapes the pattern as necessary", :unless => RSpec::Support::OS.windows? do
386:      it "shellescapes the pattern as necessary", :unless => RSpec::Support::OS.windows? do

rspec-core/spec/rspec/core_spec.rb
233:      expect(File.executable? RSpec::Core.path_to_executable).to be_truthy unless RSpec::Support::OS.windows?

rspec-core/spec/support/shared_example_groups.rb
20:  end if RSpec::Support::OS.windows?

rspec-expectations/spec/rspec/matchers/built_in/output_spec.rb
160:          if RSpec::Support::OS.windows?
172:          if RSpec::Support::OS.windows?

rspec-support/lib/rspec/support/spec.rb
51:        return if RUBY_ENGINE != 'ruby' || RSpec::Support::OS.windows?

rspec-support/spec/rspec/support/ruby_features_spec.rb
25:          stub_const("File::ALT_SEPARATOR", "\\") unless OS.windows?
30:          stub_const("File::ALT_SEPARATOR", nil) if OS.windows?

rspec-support/spec/rspec/support/spec/stderr_splitter_spec.rb
31:    stderr_methods -= [:close_on_exec?, :close_on_exec=] if RSpec::Support::OS.windows?
```

That said, I do tend to favor predicates returning stricter `true` or `false` values but don't always find it worthwhile to put the time in to do so.

I'm going to close this since it's working as designed, but I'd happily merge a PR improving the `windows?` method to return a strict `true` or `false` value, although I tend to favor the `!!` pattern:

``` ruby
def windows?
  !!(RbConfig::CONFIG['host_os'] =~ /cygwin|mswin|mingw|bccwin|wince|emx/)
end
```

**Closed by myronmarston** 2015-07-04 05:43 UTC
